export class Cum {
    constructor(
        public readonly id: string | null,
        public expediente: string,
        public producto: string,
        public titular: string,
        public registroSanitario: string,
        public fechaExpedicion: Date | null,
        public fechaVencimiento: Date | null,
        public estadoRegistro: string,
        public expedienteCum: string,
        public consecutivo: string,
        public cantidadCum: number | null,
        public descripcionComercial: string,
        public estadoCum: string,
        public fechaActivo: Date | null,
        public fechaInactivo: Date | null,
        public muestraMedica: string,
        public unidad: string,
        public atc: string,
        public descripcionAtc: string,
        public viaAdministracion: string,
        public concentracion: string,
        public principioActivo: string,
        public unidadMedida: string,
        public cantidad: string, // Often has units or ranges
        public unidadReferencia: string,
        public formaFarmaceutica: string,
        public nombreRol: string,
        public tipoRol: string,
        public modalidad: string,
        public ium: string,
        public readonly createdAt: Date | null = null,
        public readonly updatedAt: Date | null = null,
    ) { }
}
